
exports.NEW_APPLICATION = 0
exports.RECEIVED_FORM = 1
exports.RECEIVED_VERIFICATION = 2
exports.CREATE_VERIFICATION = 3
exports.SENT_VERIFICATION = 4
exports.IMPORT_SESSION = 5
exports.NEW_CUSTOMER = 6
exports.APPROVE_PRODUCT = 7
exports.SKIP_FORM = 8
exports.ASSIGN_RELATIONSHIP_MANAGER = 9
