
exports.NEW_APPLICATION = 0
exports.RECEIVED_FORM = 1
exports.RECEIVED_VERIFICATION = 2
exports.CREATE_VERIFICATION = 3
exports.SENT_VERIFICATION = 4
exports.IMPORT_SESSION = 5
exports.NEW_CUSTOMER = 6
exports.APPROVE_PRODUCT = 7
exports.APPROVED_PRODUCT = 8
exports.REVOKE_PRODUCT = 9
exports.SKIP_FORM = 10
exports.ASSIGN_RELATIONSHIP_MANAGER = 11
exports.SET_PROFILE = 12
exports.SHARE_CONTEXT = 13
exports.UNSHARE_CONTEXT = 14
